version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: gestionEcole
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network
  ge:
    container_name: ge-service
    build: 
      context: ./GE
      dockerfile: ./docker/spring-app/Dockerfile
    image: thomaslpro/gestion-ecole_partiel:latest
    depends_on:
      registration:
        condition: service_healthy
      configuration:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka 
    networks:
      - app-network
  configuration:
    container_name: config-service
    build: ./configurationService
    image: thomaslpro/config-service:latest
    ports:
      - 8888:8888
    healthcheck:
        test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
        interval: 20s
        timeout: 20s
        retries: 5
        start_period: 100s
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./cloud-conf:/cloud-conf
    networks:
      - app-network
  gateway:
    container_name: gateway
    build: ./gateway-service
    image: thomaslpro/gateway-service:latest
    depends_on:
      registration:
        condition: service_healthy
      configuration:
        condition: service_healthy
    ports:
      - 9999:9999
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka 
    networks:
      - app-network
  registration:
    container_name: registration
    build: ./registrationService
    image: thomaslpro/registration-service:latest
    depends_on:
      configuration:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 100s
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka 
    networks:
      - app-network
  angular-app:
    image: thomaslpro/compte-app:latest
    ports:
      - 80:80
    networks:
      - app-network    
networks:
  app-network:
    name: app-network
    driver: bridge
