version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: gestionEcole
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network
  ge:
    image: thomaslpro/gestion-ecole_partiel
    hostname: ge
    depends_on:
      - registration
    command: sh -c "/wait && java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -jar gestionEcole.jar"
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka
      - WAIT_HOSTS=registration:8761
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  configuration:
    image: thomaslpro/config-service
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8888:8888
    environment:
	- SPRING_PROFILES_ACTIVE=prod
	- TOKEN=token-value
    networks:
      - app-network
  gateway:
    image: thomaslpro/gateway-service
    hostname: gateway
    depends_on:
      - registration
    command: sh -c "/wait && java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -jar gateway.jar"
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 9999:9999
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka
      - WAIT_HOSTS=registration:8761
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  registration:
    image: thomaslpro/registration-service
    depends_on:
      - configuration
    command: sh -c "/wait && java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -jar registration.jar"
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka
      - WAIT_HOSTS=configuration:8888
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  angular-app:
    image: thomaslpro/compte-app
    ports:
      - 80:80
    command: sh -c "/wait && nginx -g 'daemon off;'"
    environment:
      - WAIT_HOSTS=my_app_test:8081
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: overlay
    internal: true
    attachable: true
