  - hosts: swarm-master
    tasks:
    - name: Install git, python 3.8
      apt:
        name:
          - git
        state: present
        update_cache: yes
    - name: Clone a github repository
      git:
        repo: https://github.com/DaviJam/GE-partiel
        dest: /microservices/
        version: deploy
        clone: yes
        update: yes
    - name: deploy stack
      command: chdir=/microservices/ "docker stack deploy -c docker-compose-swarn.yml my_app"
